### ISSUE TITLE
Comment Consistency

### ISSUE THREAD

**Issue by jd-solanki** [TheSecEng/ColoredComments#13]
Hello,

I am really glad that I found this in ST3. However, I have suggestion for a package which helps team to write consistent code across all editors.

As you are inspired by [this package](https://github.com/aaron-bond/better-comments) it will be great if you follow it's comment convention like for todo it is `TODO:` and in our side we have `TODO` without colon(`:`)

So, if you can make highlighting words the same as vs-code, team working on project with different editors can highlight comments in both vs-code and sublime.

BTW, it's really great :+1: 

Awaiting for your thought on this

~ Regards

**Comment by TerminalFi** [comment]
In the next release I’ll include all of the default options from BetterComments  

Thanks for the idea and issue !

**Comment by TerminalFi** [comment]
@jd-0001 

Is this what you had in mind?

<img width="175" alt="2020-03-17_13-09-30" src="https://user-images.githubusercontent.com/32599364/76882144-9b46c400-6850-11ea-84cd-e299847460e8.png">

**Comment by TerminalFi** [comment]
Resolved in #14

**Comment by jd-solanki** [comment]
exactly @TheSecEng
