### ISSUE TITLE
"Change your color scheme" prompt overly aggressive

### ISSUE THREAD

**Issue by keith-hall** [TheSecEng/ColoredComments#15]
Hi,

I just installed this package, and I like that the first thing it did was ask me:

> Would you like to change your color scheme to [...]?
  To permanently disable this prompt, set 'prompt_new_color_scheme' to false in the Colored Comments settings

:+1:

However, I pressed Cancel, as I don't want any packages to interfere with my color scheme - even a copy of it - I'd rather add what I want directly & manually. Then, I opened the Colored Comments preferences, and upon opening the new window with the side by side settings view, I received this prompt 3 more times.

Then, as I tried writing `"prompt_new_color_scheme": false,` in the right hand / user preferences pane, for every keystroke, I received the same prompt, followed by "`colored_comments.sublime-settings` has changed on disk, do you wish to reload it?"

Please could you investigate a solution to prompt less often? Maybe only prompt again after some time has elapsed, or perhaps only when switching tabs etc. so it wouldn't interfere with typing in the preferences to disable the prompt? :)

----

Also, I noticed that comments were only colored after I made a change in the view/buffer - my expectation was that it would color them as soon as the plugin is loaded. (I'm referring to files I had open already. They didn't get automatic comment coloring when this plugin was installed, nor when ST was restarted.)

---

Thanks for your hard work on this plugin btw. :)

**Comment by TerminalFi** [comment]
@keith-hall Thanks for the feedback! I will definitely working a a solution to fix the prompting.

As well as it highlighting colors on load.

**Comment by TerminalFi** [comment]
@keith-hall Would having the prompt be disabled for that session be a acceptable solution?

Basically if you aren't using a `Colored Comments` scheme file and you don't have `prompt_new_color_scheme` set to `false` it will prompt you, if you select `cancel` it will not prompt you for that session again.

**Comment by keith-hall** [comment]
sounds like a great solution to me, thanks! :)

**Comment by TerminalFi** [comment]
Awesome! as for the  below, I am working on that as well. I thought that the `sublime_plugin.EventListener.on_load()` would do this, it doesn't appear to be working as I thought. Will continue to look into that for release 2.3.1

> Also, I noticed that comments were only colored after I made a change in the view/buffer - my expectation was that it would color them as soon as the plugin is loaded. (I'm referring to files I had open already. They didn't get automatic comment coloring when this plugin was installed, nor when ST was restarted.)

**Comment by keith-hall** [comment]
a new API was added in build 4050 for this very reason, I believe - the discussion at https://github.com/sublimehq/sublime_text/issues/5 may help

**Comment by TerminalFi** [comment]
Oh thanks! I will get this resolved today then!
