### ISSUE TITLE
Can't use own color for highlighting

### ISSUE THREAD

**Issue by jd-solanki** [TheSecEng/ColoredComments#21]
Hi, Thanks for considering the previous suggestion.

I installed your plugin and I want to change the highlight color of TODO because it isn't suiting my current color scheme. So, I made following changes:

```python
{
	"old_color_scheme": "Packages/Dracula Color Scheme/Dracula.tmTheme",
	"prompt_new_color_scheme": false,
	"tags":
	{
		"TODO":
		{
			"color":
			{
				"background": "rgba(1,22,38, 0.1)",
				"foreground": "#fff",
				"name": "todo"
			}
		}
	}
}
```
But even after I close and restart sublime text it isn't working.

~ Regards

**Comment by TerminalFi** [comment]
When you change your color scheme. You need to quit ST then Regenerate Colored Comments. 

I’m investigate a better method. But as of now, it’s required

**Comment by TerminalFi** [comment]
Seems the solution worked.
