### ISSUE TITLE
[Feature Request] support for Dracula colorcsheme

### ISSUE THREAD

**Issue by salahmak** [TheSecEng/ColoredComments#31]
Hi, I have installed the package on Sublime text 3 and the coloring doesn't work as expected even after running `Colored Comments: Generate Color Scheme` many times, and then I have realized that it only works with the default sublime colorschemes (ex: Monokai...). And I use Dracula colorscheme, so I'm happy to request the support for it on this life saving package.
Thanks.

![image](https://user-images.githubusercontent.com/49586511/106180471-9d7dec80-619c-11eb-87d9-7be4be56bea0.png)

**Comment by TerminalFi** [comment]
Thanks for the issue. I’ll look at this weekend.

**Comment by salahmak** [comment]
Thanks for responding, goodluck on the issue.

**Comment by TerminalFi** [comment]
I've identified the issue and have a fix in the pipeline

**Comment by salahmak** [comment]
that's great, thanks for putting effort into this. I appreciate it

**Comment by TerminalFi** [comment]
fix released

**Comment by salahmak** [comment]
it works fine now, thanks so much
