### ISSUE TITLE
Can't generate color scheme

### ISSUE THREAD

**Issue by sh4nks** [TheSecEng/ColoredComments#32]
I am always getting this error:

```
Traceback (most recent call last):
  File "C:\Apps\Sublime Text\Lib\python38\sublime_plugin.py", line 1518, in run_
    return self.run(edit)
  File "C:\Apps\Sublime Text\Data\Installed Packages\Colored Comments.sublime-package\colored_comments.py", line 79, in run
AttributeError: 'NoneType' object has no attribute 'create_user_custom_theme'
```

**Comment by TerminalFi** [comment]
Thanks for the report. I think I know the issue here.

**Comment by TerminalFi** [comment]
I am pushing out a new ST4 release which resolves this issue. Moving to no longer auto generating color scheme modifications. And allowing the user to override there color scheme manually. This will solve these issues.

**Comment by sh4nks** [comment]
Thanks!

**Comment by TerminalFi** [comment]
Alright, the new release is done.

1. Users now have to override there color scheme manually to create rules.

It is ST4 only release
