### ISSUE TITLE
Coloring every comment as undefined_comment

### ISSUE THREAD

**Issue by sollymay** [TheSecEng/ColoredComments#38]
Seems like after configuring, all comments show as undefined coloring, even when I explicitly use different colors for each:
<img width="191" alt="Screen Shot 2021-12-15 at 5 15 16 PM" src="https://user-images.githubusercontent.com/6496698/146273508-3334f324-baec-4d45-a79b-8ad35942ef28.png">

<img width="405" alt="Screen Shot 2021-12-15 at 5 17 47 PM" src="https://user-images.githubusercontent.com/6496698/146273620-cefbe7c1-2978-447c-8c07-8b3200922219.png">

I am using default settings and just tried to hardcode values to make sure that everything worked, but ended up getting all comments as "undefined" comments.

**Comment by TerminalFi** [comment]
Thanks, I am planning to dig into this soon

**Comment by TerminalFi** [comment]
ST Version?
