### ISSUE TITLE
Support comments from Doc​Blockr

### ISSUE THREAD

**Issue by mauroreisvieira** [TheSecEng/ColoredComments#6]
Hi @TheSecEng it's very good plugin.

Your plugin can support this kind of comments?

![Screenshot 2020-03-09 at 09 47 01](https://user-images.githubusercontent.com/3084774/76201398-18d45980-61eb-11ea-8e67-28805a90dfba.png)

**Comment by TerminalFi** [comment]
To ensure I understand , both sentences should be highlighted ?

**Comment by mauroreisvieira** [comment]
No, I talk about @param and {string}.

The description it's good as is.

**Comment by TerminalFi** [comment]
> No, I talk about @param and {string}.
> 
> The description it's good as is.

Sure just add @param as the identifier and it should work as expected. If you wait till I update it today it will also resolve some issues with color scheme generation that I overlooked before.

**Comment by mauroreisvieira** [comment]
Ok, I try but not work as expected.

![Screenshot 2020-03-09 at 13 56 21](https://user-images.githubusercontent.com/3084774/76219483-ce180900-620d-11ea-9bf4-7066f7fdc212.png)

Is not possible to use the variables form the scheme?

instead of `region.greenish` using the `var(green)` directly? 

by the way, I wait for your next update.

**Comment by TerminalFi** [comment]
> Ok, I try but not work as expected.
> 
> ![Screenshot 2020-03-09 at 13 56 21](https://user-images.githubusercontent.com/3084774/76219483-ce180900-620d-11ea-9bf4-7066f7fdc212.png)
> 
> Is not possible to use the variables form the scheme?
> 
> instead of `region.greenish` using the `var(green)` directly?
> 
> by the way, I wait for your next update.

Currently no, the update will contain this feature

**Comment by TerminalFi** [comment]
@mauroreisvieira I've pushed changes and issued a new release that supports `variables` by removing color validation and relying on ST to do that as they already do.

You can either wait from PackageControl to re-pull the new release or do a `git clone git@github.com:TheSecEng/ColoredComments.git "Colored Comments"` into your Packages directory.

**Comment by TerminalFi** [comment]
Although, I just noticed multiline comments don't get treated correctly, so it appears I have more work to do 😄 

<img width="168" alt="2020-03-09_12-32-22" src="https://user-images.githubusercontent.com/32599364/76235821-07e31280-6202-11ea-9793-2805710d202b.png">

The colors are getting triggered on the `*` which is wrong. So I will work on this tonight

**Comment by mauroreisvieira** [comment]
Yeh. My idea it's only set the color to @param and the type. :)

**Comment by TerminalFi** [comment]
> Yeh. My idea it's only set the color to @param and the type. :)

Awesome, v2.0.4 will have a fix for this by supporting regex inside of the identifier.

**Comment by mauroreisvieira** [comment]
Hi @TheSecEng look amazing! Thanks for you work!

**Comment by mauroreisvieira** [comment]
Strange, In typescript work's fine, but in javascript not:

<img width="492" alt="Screenshot 2020-03-09 at 21 14 56" src="https://user-images.githubusercontent.com/3084774/76258265-228da980-624b-11ea-958f-474beecde4e5.png">


do you know what's appen?

**Comment by TerminalFi** [comment]
@mauroreisvieira fix is delayed, in the mean time you can make an identifier like "* @param" and it will work.

**Comment by TerminalFi** [comment]
Resolved in #7

**Comment by TerminalFi** [comment]
@mauroreisvieira once PackageControl updates Colored Comments to 2.1.0 I recommend you write a tag like this for multiple matching.

```json
"@Param":
{
	"color":
	{
		"background": "rgba(1,22,38, 0.1)",
		"foreground": "#00cc00",
		"name": "Param"
	},
	"identifier": "[\\*]?[ ]?@param",
	"is_regex": true,
	"priority": "-9999"
}
```

I am sure you know but the `?` make those characters optional for matching which is what allows it to match both `@param` and `* @param`
It will allow you to match the following cases.

```java
/*
@param MyFunction
* @param MyFunction
*/
```

<img width="228" alt="2020-03-11_21-30-23" src="https://user-images.githubusercontent.com/32599364/76478574-8648db80-63df-11ea-9d94-78f3560f62d1.png">

**Comment by mauroreisvieira** [comment]
Thanks!
